#!/bin/bash
# -*- shell-script -*-
OUTPUT=/tmp/test-output.txt

EMACS_BINARY="emacs"

EMACS_VERSION=$1
if [ -n "$EMACS_VERSION" ]; then
    EMACS_BINARY=`evm bin $EMACS_VERSION`
fi

LOAD_FILES="-l ert-bootstrap.el -l elixir-mode-tests.el"

$EMACS_BINARY -batch $LOAD_FILES -f ert-run-tests-batch-and-exit 2> $OUTPUT

if [ $? == 0 ]; then
    echo "Success -- All tests passed."
    rm $OUTPUT
else
    # Give the user to re-do the tests in emacs proper
    cat /tmp/test-output.txt
    while [[ 1 ]]
    do
        read -p "There were test failures. Re-run in regular Emacs? [Yn]" choice
        case $choice in
            n|N)
                break
                ;;
            *)
                $EMACS_BINARY -q $LOAD_FILES -f ert-run-tests-interactively
                break
                ;;
        esac
    done
fi

